from .SignUpViewTests import SignUpViewTests
from .SignInViewTests import SignInViewTests
from .SignUpViewTests import UsernameUniqueCheckTests

from .FriendRequestViewTests import FriendRequestViewTests
from .TeamViewTests import TeamViewTests
from .TeamInvitationViewTests import TeamInvitationViewTests
from .MatchViewTests import MatchViewTests
from .MatchInvitationViewTests import MatchInvitationViewTests
