# Generated by Django 4.2.14 on 2024-09-14 18:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('team_size', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.FloatField(default=0.0)),
                ('positions', models.JSONField(default=list)),
                ('kit_number', models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(99)])),
                ('goals', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('mvp', models.IntegerField(default=0)),
                ('join_date', models.DateField(auto_now_add=True)),
                ('setup_complete', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, default=None, null=True)),
                ('friends', models.ManyToManyField(to='sidelines_django_app.profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('overall_rating', models.FloatField(default=0.0)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('admins', models.ManyToManyField(related_name='admin_teams', to='sidelines_django_app.profile')),
                ('members', models.ManyToManyField(related_name='teams', to='sidelines_django_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='sidelines_django_app.profile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='sidelines_django_app.team')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='sidelines_django_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_size', models.IntegerField(default=7)),
                ('location', models.CharField(max_length=255)),
                ('date_time', models.DateTimeField()),
                ('from_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='sidelines_django_app.team')),
                ('to_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to='sidelines_django_app.team')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0)),
                ('shooting', models.PositiveIntegerField(default=0)),
                ('attacks', models.PositiveIntegerField(default=0)),
                ('possession', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('fouls', models.PositiveIntegerField(default=0)),
                ('corners', models.PositiveIntegerField(default=0)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='sidelines_django_app.match')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidelines_django_app.team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sidelines_django_app.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sidelines_django_app.team'),
        ),
        migrations.CreateModel(
            name='FriendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_requests', to='sidelines_django_app.profile')),
                ('to_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_requests', to='sidelines_django_app.profile')),
            ],
        ),
        migrations.CreateModel(
            name='MatchVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('accepted', 'Accepted'), ('rejected', 'Rejected'), ('maybe', 'Maybe')], default='maybe', max_length=10)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='sidelines_django_app.match')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sidelines_django_app.profile')),
            ],
            options={
                'unique_together': {('match', 'profile')},
            },
        ),
    ]
