# Generated by Django 4.2.14 on 2024-09-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sidelines_django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
