# Generated by Django 4.2.14 on 2024-08-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sidelines_django_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchinvitation',
            name='admin_approved',
        ),
    ]
